### ISSUE TITLE
React.createClass is not a function

### ISSUE THREAD

**Issue by jenyckee** [cultureamp/react-elm-components#17]
React.createClass is no longer [supported](https://reactjs.org/docs/react-without-es6.html). Causes it to break here:

`React.createClass is not a function`

**Comment by sentience** [comment]
See #10, #11, and #14.

**Comment by mcmunder** [comment]
This problem still exists for me! Reopen the issue?!

**Comment by sentience** [comment]
@mcmunder The issue was fixed on master but has not yet been released to NPM in a new version of the package. If you point your package.json at this repo (`"react-elm-components": "evancz/react-elm-components"`) you should get the fix.

**Comment by mcmunder** [comment]
thx @sentience! I did that and it works as expected.
