### ISSUE TITLE
Demo maxes out CPU usage in Chrome for me

### ISSUE THREAD

**Issue by JobLeonard** [cultureamp/react-elm-components#2]
Chrome tends to do so when loading a new page anyway, but here it seems stuck. I recorded my desktop to show:

https://youtu.be/SPKh7dlDvI8

I wouldn't be surprised if it actually is a Chrome bug, but it's still annoying that it causes my laptop to freeze and ignore half of the input (including making it hard to close the tab). I don't have this issue with Firefox.

Running Ubuntu 16.04

**Comment by evancz** [comment]
Interesting, thanks for the video!

If you modify `index.jsx` to take out the emoji picker, does it still go wrong?

If you take out the Elm websocket stuff, does it still go wrong?

This will localize the problem to Elm things or the somewhat crazy emoji picker I got off the shelf. It actually loads ALL the emoji as images all at once from some CDN, so that'd be my theory on what's up.

Anyway, let me know the results of those two questions!

**Comment by JobLeonard** [comment]
Writing this during breakfast; will try your suggestions later during a break at work.

It seems it is no longer stuck... what _does_ happen, trying this gain, is that in _any_ browser, CPU usage is maximised for a while. Could there be some poorly coded webworker thing going on? Because it's rare that a website maxes out _all_ of my cores, and my first guess would be that yesterday it got stuck waiting for an emoji to download.

**Comment by evancz** [comment]
Nothing like that in any Elm code. I suspect that browsers can spin up worker threads for downloads, and since the React component is triggering literally hundreds of simultaneous image downloads, I can see something like this happening.

**Comment by JobLeonard** [comment]
I'll try your suggestions from earlier and if it's the emoji picker we can safely close this (and open an issue on the Emoji Picker page about using sprite sheets or something). However, there's a small issue:

```
job@job-ThinkPad-T440s-Ubuntu ~/D/e/react-elm-components> npm install
npm WARN react-elm-components@1.0.0 requires a peer of react@>=0.14.0 but none was installed.
 job@job-ThinkPad-T440s-Ubuntu ~/D/e/react-elm-components> npm run serve
npm ERR! Linux 4.4.0-28-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "serve"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.4

npm ERR! missing script: serve
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/job/Dev/elm/react-elm-components/npm-debug.log
```

**Comment by evancz** [comment]
Can you work through this with someone on the Elm slack? It seems like some `npm` issue where it's not installing things right, and someone on slack can help work through it better than me.

**Comment by evancz** [comment]
Not sure how to resolve this without further information. Please reopen if you can pin the problem to something Elm related.

**Comment by JobLeonard** [comment]
Yeah, my apologies, haven't gotten around to figuring out how to consistently reproduce it. Will re-open if that ever happens.
